name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Change this to your target branch if needed
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push-image-to-ecr:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        flavor: |
          latest=true
        with:
          images: coding-jjun/giftogether
          tags: |
            type=sha,format=short
            type=raw,value=latest,enable=${{is_default_branch}}
      
      - name: test metatags
        run: |
            echo "steps.meta.outputs.tags=${{ steps.meta.outputs.tags }}"
            echo "steps.meta.outputs.labels=${{ steps.meta.outputs.labels }}"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t giftogether -f Dockerfile .

      - name: Tag Docker image
        run: |
          # Tag the image with the ECR repository URI
          docker tag giftogether ${{ secrets.REGISTRY }}/coding-jjun/giftogether:${{steps.meta.outputs.tags}}

      - name: Push Docker image to ECR
        run: |
          # Push the Docker image to your ECR repository
          docker push ${{ secrets.REGISTRY }}/coding-jjun/giftogether:${{ github.sha }}
