name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Change this to your target branch if needed
  pull_request:
    branches:
      - main
    # types:
    #   - closed

jobs:
  build-and-push-image-to-ecr:
    # if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{secrets.REGISTRY}}/coding-jjun/giftogether
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: test metatags
        run: |
            echo "steps.meta.outputs.tags=${{ steps.meta.outputs.tags }}"
            echo "steps.meta.outputs.labels=${{ steps.meta.outputs.labels }}"

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        uses: docker/bake-action@5.10.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
        targets: build

      - name: Push Docker image to ECR
        uses: docker/build-push-action@v6.9.0
        with:
          build-args: |
            DOCKER_METADATA_OUTPUT_JSON
